color:
  saturation: 0.2701396
  brandStrength: 0.8044979
  rhythmicContrast: 0.5633727
  brandColors:
    - '#FEFEFE'
    - '#FDC40D'
    - '#B1D135'
    - '#5D5E5D'
    - '#A8A5A5'
  lightness: 0.2679914
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.2250268
typography_spectrum: 0.6675618
name: 'L&LBricks'
