name: 'L & LBricks'
favicon: null
layout_spectrum: 0.2250268
typography_spectrum: 0.6675618
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: 'L & L Bricks'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FEFEFE'
    - '#FDC40D'
    - '#B1D135'
    - '#5D5E5D'
    - '#A8A5A5'
  brandStrength: 0
  lightness: 0.2679914
  saturation: 0.2701396
  rhythmicContrast: 0.5633727
purpose: []
